<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/Admin.master" AutoEventWireup="true" CodeFile="StudentReport.aspx.cs" Inherits="Staff_StudentReport" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <style type="text/css">
        .style4
    {
        width: 535px;
    }
    .style5
    {
        width: 45px;
    }
    .style6
    {
        width: 140px;
    }
    .style7
    {
        text-align: right;
        color: Red;
        width: 121px;
    }
    .style8
    {
        width: 121px;
    }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <table class="tbl">
        <tr>
            <td class="tblhead">
                STUDENT REPORTS</td>
        </tr>
        <tr>
            <td>
                &nbsp;</td>
        </tr>
        <tr>
            <td style="text-align: left">
            <table align="left" class="style4">
                <tr>
                    <td class="style7">
                        &nbsp;</td>
                    <td class="style6">
                        &nbsp;</td>
                    <td class="style5">
                        &nbsp;</td>
                    <td>
                        &nbsp;</td>
                </tr>
                <tr>
                    <td class="style7">
                        &nbsp;</td>
                    <td class="style6">
                        &nbsp;</td>
                    <td class="style5">
                        &nbsp;</td>
                    <td>
                        &nbsp;</td>
                </tr>
                <tr>
                    <td class="style8">
                        &nbsp;</td>
                    <td class="style6">
                        &nbsp;</td>
                    <td class="style5">
                        &nbsp;</td>
                    <td>
                        &nbsp;</td>
                </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td>
                <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" 
                    CellPadding="4" ForeColor="#333333" GridLines="None" Width="718px" 
                    AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" 
                    DataKeyNames="Hostel_RollNo" DataSourceID="SqlDataSource1">
                    <AlternatingRowStyle BackColor="White" />
                    <Columns>
                        <asp:BoundField DataField="Hostel_RollNo" HeaderText="Hostel_RollNo" ReadOnly="True" 
                            SortExpression="Hostel_RollNo" />
                        <asp:BoundField DataField="Student_Name" HeaderText="Student_Name" 
                            SortExpression="Student_Name" />
                        <asp:BoundField DataField="Mobile" HeaderText="Mobile" 
                            SortExpression="Mobile" />
                        <asp:BoundField DataField="Email" HeaderText="Email" SortExpression="Email" />
                        <asp:BoundField DataField="DOB" HeaderText="DOB" SortExpression="DOB" />
                        <asp:BoundField DataField="Password" HeaderText="Password" 
                            SortExpression="Password" />
                        <asp:BoundField DataField="Total_Diet" HeaderText="Total_Diet" 
                            SortExpression="Total_Diet" />
                        <asp:BoundField DataField="Extra" HeaderText="Extra" SortExpression="Extra" />
                    </Columns>
                    <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                    <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
                    <RowStyle BackColor="#FFFBD6" ForeColor="#333333" />
                    <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy" />
                    <SortedAscendingCellStyle BackColor="#FDF5AC" />
                    <SortedAscendingHeaderStyle BackColor="#4D0000" />
                    <SortedDescendingCellStyle BackColor="#FCF6C0" />
                    <SortedDescendingHeaderStyle BackColor="#820000" />
                </asp:GridView>
            </td>
        </tr>
        <tr>
            <td>
                <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
                    ConnectionString="<%$ ConnectionStrings:abcConnectionString %>" 
                    DeleteCommand="DELETE FROM [Registration_Form] WHERE [Hostel_RollNo] = @Hostel_RollNo" 
                    InsertCommand="INSERT INTO [Registration_Form] ([Hostel_RollNo], [Student_Name], [Mobile], [Email], [DOB], [Password], [Total_Diet], [Extra]) VALUES (@Hostel_RollNo, @Student_Name, @Mobile, @Email, @DOB, @Password, @Total_Diet, @Extra)" 
                    SelectCommand="SELECT * FROM [Registration_Form]" 
                    
                    
                    
                    UpdateCommand="UPDATE [Registration_Form] SET [Student_Name] = @Student_Name, [Mobile] = @Mobile, [Email] = @Email, [DOB] = @DOB, [Password] = @Password, [Total_Diet] = @Total_Diet, [Extra] = @Extra WHERE [Hostel_RollNo] = @Hostel_RollNo">
                    <DeleteParameters>
                        <asp:Parameter Name="Hostel_RollNo" Type="String" />
                    </DeleteParameters>
                    <InsertParameters>
                        <asp:Parameter Name="Hostel_RollNo" Type="String" />
                        <asp:Parameter Name="Student_Name" Type="String" />
                        <asp:Parameter Name="Mobile" Type="String" />
                        <asp:Parameter Name="Email" Type="String" />
                        <asp:Parameter Name="DOB" Type="String" />
                        <asp:Parameter Name="Password" Type="String" />
                        <asp:Parameter Name="Total_Diet" Type="Int32" />
                        
                        <asp:Parameter Name="Extra" Type="Int32" />
                        
                    </InsertParameters>
                    <UpdateParameters>
                        <asp:Parameter Name="Student_Name" Type="String" />
                        <asp:Parameter Name="Mobile" Type="String" />
                        <asp:Parameter Name="Email" Type="String" />
                        <asp:Parameter Name="DOB" Type="String" />
                        <asp:Parameter Name="Password" Type="String" />
                        <asp:Parameter Name="Total_Diet" Type="Int32" />
                       
                        <asp:Parameter Name="Extra" Type="Int32" />
                        <asp:Parameter Name="Hostel_RollNo" Type="String" />
                    </UpdateParameters>
                </asp:SqlDataSource>
            </td>
        </tr>
    </table>
</asp:Content>

